list = []
a = int(input("Enter the 1 value:"))
list.append(a)
b = int(input("Enter the 1 value:"))
list.append(b)
c = int(input("Enter the 1 value:"))
list.append(c)
d = int(input("Enter the 1 value:"))
list.append(d)
e = int(input("Enter the 1 value:"))
list.append(e)
print(list)
no_dup=set(list)
print(no_dup)
